language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
    - node_modules
script:
- npm run build
deploy:
    proider:script
    script: "[[ -z $TRAVIS_TAG ]] || mvn clean deploy --settings settings.xml"
    on:
      branch: master
global:
    env:
  - secure: 2jTgjWgET+AErTk0YzskhyS+BQlXXmJI0SmElEYRDU03Z5llRBtUU08jegfbbZFSqosyjRYdO6QDQT8bUwqeDaPT7mKXTy7S4Xyxy0HJb6EmG/oukm7iDDoI4heW9wafrf+eOe+UiuO1j3cVuMo8p/7oc7vZCMKQljSiKe/u6r6blid6g18bOawCgnOs0GMiza4gHQpcwzcu7oVfkgxTCET+yXFJE0wKkVjL0c3VbxHX3GdBr8swVPZsg6GExiy+r0Hvbf6PoTPkCeUtvDDQDbgCdpwt3zgnyf1cA5SI2DBWOQZRtHUvyADjmmj/FO19iFwinnY7D15FK4FMo2zttCUBgHpmor5ePyfqs9GXDJJmnhIjHdZ4euMEFHOAWAE8i5cKjFZVV4U6k2jX31onRNlpOPlei3dGvXVZIdeTqLphv6ZT+6vIaDN3GTE/SVu14W5Ha+NkIpK1riKwnLKEWNbd93bcXMq3E371Qg2UhNWcq63GU89JU5UC2oggkOvpAoDfKh/vza5mGRrso0pgBgHnNq9KFMDj6AOR6J5qUBLYQvPi5XdiGzr+trniLVtVHAIcoBMLL7TFBEEXNadw0EV/zocuufjhfeEX5QeQumqWDU7UDUrmAPGrEJ9YH/xv/NLg+NYYKCOCiFKBxKIthqrqOVECtBw46ysvkaHo720=
  - secure: tMkaspkJPgDhb8STLdkd0Pdc8u0F+HMMp+cW3SVQgI+pvpzvUgRmgiTh1ZbfZitmeGPNq863U1GeuS5hHm+QKs1YV6xE+57oAqnNoPGaeHFy/SaMjAo7D0LxcgPYuxrHaBoH9gRKhgYoWuMz/9bfGGDNKck14MYdzpesVf5PCkKEr8TNvr5G//a1SkFB4D9Y0fdc5Hc6DBBctcXN3PbULA/s9sQO1z2utSx1ypYn203ubCVDJ1BmqyP3dnebAmqT5UuyEijx+3msGR+T03mBnUr2SnPrD2nXb4aPWTuCgL8jt8Qs5Rj85WDhkj4rIqaWL810aMyZgJYhg+x90mjC1x6RwbJ+vx5n0I6gwEeXdzW3/0oUXFDGlmTLuuEw+bYo0AALhbygb2nz+rhYI/vfZBQwVBhwLe0ZTlUU8Ioc/hToUmISIN+o3dO7GYxEqEF0OlQy1V13rTx42UlkRv9+CTcXV4+GgIn4LFFrfRPbKRCFuUkPvRxoSAqt/cXCX6P/KyV9RP6RcE8QmOqbVVAKG6j7uFFh53eXEEdbX7/8MovEont3QPst6IGbPqzV11zpSs4o/dWfsGVMg8egjrmqef1WwPR/AYNek6uRjgFMnb7xk2lXTTKVN0G7O9H8UJRch95NaVPVogntvzQHb6r95OFK8PaEAcVnHe90q4CRy7k=
